# Generated by Django 3.2.7 on 2021-10-28 05:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_name', models.CharField(max_length=250)),
                ('faculty_speciality', models.CharField(max_length=250)),
                ('faculty_id', models.UUIDField(default=uuid.uuid5, primary_key=True, serialize=False)),
                ('faculty_call_charges', models.IntegerField()),
                ('faculty_ratings', models.IntegerField()),
                ('faculty_category', models.CharField(max_length=240)),
                ('faculty_online', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12)),
                ('user_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserVerification',
            fields=[
                ('email', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('otp', models.CharField(max_length=4)),
            ],
        ),
    ]
