# Generated by Django 3.2.7 on 2021-10-28 05:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('UserApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_name', models.CharField(max_length=250)),
                ('faculy_speciality', models.CharField(max_length=250)),
                ('faculty_id', models.UUIDField(default=uuid.uuid5, primary_key=True, serialize=False)),
                ('faculty_call_charges', models.IntegerField()),
                ('faculty_ratings', models.IntegerField()),
                ('faculty_category', models.CharField(max_length=240)),
                ('faculty_online', models.BooleanField(default=True)),
            ],
        ),
    ]
