# Generated by Django 3.2.7 on 2021-10-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='faculty_call_charges',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='faculty_ratings',
            field=models.CharField(max_length=20),
        ),
    ]
