# Generated by Django 3.2.7 on 2021-10-29 12:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('UserApi', '0003_alter_faculty_faculty_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('user_id', models.CharField(max_length=250, unique=True)),
                ('wallet_id', models.UUIDField(default=uuid.UUID('3def2253-4c8a-4161-8e7d-edca58da0109'), primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('transactions', models.JSONField()),
            ],
        ),
    ]
