# Generated by Django 3.2.7 on 2021-10-29 12:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('UserApi', '0004_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.UUIDField(default=uuid.UUID('26d0c896-bb7e-423e-9059-483fc58d1d3c'), primary_key=True, serialize=False),
        ),
    ]
